# Generated by Django 6.0.1 on 2026-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.TextField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_num', models.IntegerField(blank=True, null=True)),
                ('street_name', models.TextField()),
                ('apt_num', models.CharField(blank=True, max_length=10, null=True)),
                ('zip', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_registration', models.DateField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=2, null=True)),
                ('precinct', models.CharField(blank=True, max_length=10, null=True)),
                ('v20', models.BooleanField(blank=True, null=True)),
                ('v21town', models.BooleanField(blank=True, null=True)),
                ('v21primary', models.BooleanField(blank=True, null=True)),
                ('v22', models.BooleanField(blank=True, null=True)),
                ('v23', models.BooleanField(blank=True, null=True)),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
